version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/kuuga

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - kuuga-deps-{{ checksum "project.clj" }}
          - kuuga-deps-

      - run: lein with-profile +merged deps

      - save_cache:
          paths:
            - ~/.m2
          key: kuuga-deps-{{ checksum "project.clj" }}

      - run: lein cljsbuild
      - run: lein all test
      - run: jjs target/nashorn/test.js
      - run: lein cloverage
      - run: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
